name: 'Deploy to github pages'
on:
  push:
    branches:
      - main
jobs:
  gh-pages-deploy:
    name: Deploying to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v2
        with:
          version:  12.x
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Clean install dependencies
        run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi

      - name: Run deploy script
        run: |
          git config user.name "maye-msft" && git config user.email "maye-msft@outlook.con"
          npm run gh-pages-deploy